spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=vaj_dev;encrypt=true;trustServerCertificate=true
    username: sa
    password: YourStrong!Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration

jwt:
  secret: Y2hhbmdlLXRoaXMtdG8tYS1sb25nLXNlY3VyZS1rZXktaW4tcHJvZHVjdGlvbi1lbnZpcm9ubWVudA==
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000