-- V001__Create_Users.sql
CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    Username NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    PasswordHash NVARCHAR(500) NOT NULL,
    Status NVARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy UNIQUEIDENTIFIER NULL,
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedBy UNIQUEIDENTIFIER NULL,
    DeletedAt DATETIME2 NULL,
    DeletedBy UNIQUEIDENTIFIER NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    Version INT NOT NULL DEFAULT 0,
    CONSTRAINT PK_Users PRIMARY KEY (Id)
);

CREATE UNIQUE INDEX IX_Users_Email ON Users (Email) WHERE IsDeleted = 0;
CREATE UNIQUE INDEX IX_Users_Username ON Users (Username) WHERE IsDeleted = 0;
CREATE INDEX IX_Users_Status ON Users (Status);
CREATE INDEX IX_Users_CreatedAt ON Users (CreatedAt);