-- V003__Create_User_Profiles.sql
CREATE TABLE UserProfiles (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    DisplayName NVARCHAR(100) NULL,
    Bio NVARCHAR(500) NULL,
    AvatarUrl NVARCHAR(500) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_UserProfiles PRIMARY KEY (Id),
    CONSTRAINT FK_UserProfiles_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
    CONSTRAINT UQ_UserProfiles_UserId UNIQUE (UserId)
);

-- V004__Create_User_Preferences.sql
CREATE TABLE UserPreferences (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Language NVARCHAR(10) NOT NULL DEFAULT 'en',
    Timezone NVARCHAR(50) NOT NULL DEFAULT 'UTC',
    Theme NVARCHAR(20) NOT NULL DEFAULT 'LIGHT',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_UserPreferences PRIMARY KEY (Id),
    CONSTRAINT FK_UserPreferences_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
    CONSTRAINT UQ_UserPreferences_UserId UNIQUE (UserId)
);