CREATE TABLE Publishers (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    Website NVARCHAR(500) NULL,
    Country NVARCHAR(10) NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy UNIQUEIDENTIFIER NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy UNIQUEIDENTIFIER NULL,
    DeletedAt DATETIME2 NULL,
    DeletedBy UNIQUEIDENTIFIER NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    Version ROWVERSION NOT NULL
);

CREATE UNIQUE NONCLUSTERED INDEX UQ_Publishers_Name ON Publishers(Name) WHERE IsDeleted = 0;
CREATE NONCLUSTERED INDEX IX_Publishers_Name ON Publishers(Name) WHERE IsDeleted = 0;