-- V011__Create_Reading_Sessions.sql
CREATE TABLE ReadingSessions (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    BookId UNIQUEIDENTIFIER NOT NULL,
    StartPage INT NULL,
    EndPage INT NULL,
    DurationMs BIGINT NULL,
    StartedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    EndedAt DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy UNIQUEIDENTIFIER NULL,
    CONSTRAINT PK_ReadingSessions PRIMARY KEY (Id),
    CONSTRAINT FK_ReadingSessions_Books FOREIGN KEY (BookId) REFERENCES Books(Id),
    CONSTRAINT CK_ReadingSessions_Duration CHECK (DurationMs >= 0),
    CONSTRAINT CK_ReadingSessions_Pages CHECK (StartPage > 0 AND EndPage >= StartPage)
);
CREATE INDEX IX_ReadingSessions_BookId ON ReadingSessions (BookId);
CREATE INDEX IX_ReadingSessions_StartedAt ON ReadingSessions (StartedAt);

-- V012__Create_Bookmarks.sql
CREATE TABLE Bookmarks (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    BookId UNIQUEIDENTIFIER NOT NULL,
    PageNumber INT NOT NULL,
    Title NVARCHAR(200) NULL,
    Note NVARCHAR(max) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy UNIQUEIDENTIFIER NULL,
    CONSTRAINT PK_Bookmarks PRIMARY KEY (Id),
    CONSTRAINT FK_Bookmarks_Books FOREIGN KEY (BookId) REFERENCES Books(Id),
    CONSTRAINT CK_Bookmarks_Page CHECK (PageNumber > 0)
);
CREATE INDEX IX_Bookmarks_BookId ON Bookmarks (BookId);

-- V013__Create_Highlights.sql
CREATE TABLE Highlights (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    BookId UNIQUEIDENTIFIER NOT NULL,
    ReadingSessionId UNIQUEIDENTIFIER NULL,
    Content NVARCHAR(max) NOT NULL,
    PageNumber INT NULL,
    Chapter NVARCHAR(200) NULL,
    Color NVARCHAR(20) NOT NULL DEFAULT 'YELLOW',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy UNIQUEIDENTIFIER NULL,
    CONSTRAINT PK_Highlights PRIMARY KEY (Id),
    CONSTRAINT FK_Highlights_Books FOREIGN KEY (BookId) REFERENCES Books(Id),
    CONSTRAINT FK_Highlights_Sessions FOREIGN KEY (ReadingSessionId) REFERENCES ReadingSessions(Id),
    CONSTRAINT CK_Highlights_Page CHECK (PageNumber > 0)
);
CREATE INDEX IX_Highlights_BookId ON Highlights (BookId);

-- V014__Create_Book_Notes.sql
CREATE TABLE BookNotes (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    BookId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(500) NOT NULL,
    Content NVARCHAR(max) NOT NULL,
    Type NVARCHAR(20) NOT NULL DEFAULT 'GENERAL',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy UNIQUEIDENTIFIER NULL,
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedBy UNIQUEIDENTIFIER NULL,
    Version INT NOT NULL DEFAULT 0,
    CONSTRAINT PK_BookNotes PRIMARY KEY (Id),
    CONSTRAINT FK_BookNotes_Books FOREIGN KEY (BookId) REFERENCES Books(Id)
);
CREATE INDEX IX_BookNotes_BookId ON BookNotes (BookId);

-- V015__Create_Collections.sql
CREATE TABLE Collections (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(1000) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy UNIQUEIDENTIFIER NULL,
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedBy UNIQUEIDENTIFIER NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    Version INT NOT NULL DEFAULT 0,
    CONSTRAINT PK_Collections PRIMARY KEY (Id),
    CONSTRAINT FK_Collections_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);
CREATE INDEX IX_Collections_UserId ON Collections (UserId);

-- V016__Create_Collection_Books.sql
CREATE TABLE CollectionBooks (
    CollectionId UNIQUEIDENTIFIER NOT NULL,
    BookId UNIQUEIDENTIFIER NOT NULL,
    AddedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_CollectionBooks PRIMARY KEY (CollectionId, BookId),
    CONSTRAINT FK_CollectionBooks_Collections FOREIGN KEY (CollectionId) REFERENCES Collections(Id),
    CONSTRAINT FK_CollectionBooks_Books FOREIGN KEY (BookId) REFERENCES Books(Id)
);

-- V017__Create_Tags.sql
CREATE TABLE Tags (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT PK_Tags PRIMARY KEY (Id),
    CONSTRAINT FK_Tags_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
    CONSTRAINT UQ_Tags_UserId_Name UNIQUE (UserId, Name)
);

-- V018__Create_Book_Tags.sql
CREATE TABLE BookTags (
    BookId UNIQUEIDENTIFIER NOT NULL,
    TagId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT PK_BookTags PRIMARY KEY (BookId, TagId),
    CONSTRAINT FK_BookTags_Books FOREIGN KEY (BookId) REFERENCES Books(Id),
    CONSTRAINT FK_BookTags_Tags FOREIGN KEY (TagId) REFERENCES Tags(Id)
);

-- V019__Create_Reading_Goals.sql
CREATE TABLE ReadingGoals (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    LibraryId UNIQUEIDENTIFIER NULL,
    Title NVARCHAR(200) NOT NULL,
    GoalType NVARCHAR(20) NOT NULL,
    TargetValue INT NOT NULL,
    CurrentValue INT NOT NULL DEFAULT 0,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    Status NVARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    Version INT NOT NULL DEFAULT 0,
    CONSTRAINT PK_ReadingGoals PRIMARY KEY (Id),
    CONSTRAINT FK_ReadingGoals_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
    CONSTRAINT FK_ReadingGoals_Libraries FOREIGN KEY (LibraryId) REFERENCES Libraries(Id),
    CONSTRAINT CK_ReadingGoals_Target CHECK (TargetValue > 0),
    CONSTRAINT CK_ReadingGoals_Current CHECK (CurrentValue >= 0)
);
CREATE INDEX IX_ReadingGoals_UserId ON ReadingGoals (UserId);
CREATE INDEX IX_ReadingGoals_Status ON ReadingGoals (Status);