CREATE TABLE ReadingSessions (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    BookId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    StartPage INT NULL,
    EndPage INT NULL,
    DurationMinutes INT NULL,
    State NVARCHAR(20) NOT NULL DEFAULT 'STARTED',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy UNIQUEIDENTIFIER NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy UNIQUEIDENTIFIER NULL,
    DeletedAt DATETIME2 NULL,
    DeletedBy UNIQUEIDENTIFIER NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    Version ROWVERSION NOT NULL
);
CREATE NONCLUSTERED INDEX IX_ReadingSessions_BookId ON ReadingSessions(BookId) WHERE IsDeleted = 0;
CREATE NONCLUSTERED INDEX IX_ReadingSessions_UserId ON ReadingSessions(UserId) WHERE IsDeleted = 0;

CREATE TABLE Bookmarks (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    BookId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Page INT NULL,
    Chapter NVARCHAR(200) NULL,
    Title NVARCHAR(200) NULL,
    Description NVARCHAR(1000) NULL,
    Color NVARCHAR(20) NULL,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy UNIQUEIDENTIFIER NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy UNIQUEIDENTIFIER NULL,
    DeletedAt DATETIME2 NULL,
    DeletedBy UNIQUEIDENTIFIER NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    Version ROWVERSION NOT NULL
);
CREATE NONCLUSTERED INDEX IX_Bookmarks_BookId ON Bookmarks(BookId) WHERE IsDeleted = 0;

CREATE TABLE ReadingGoals (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    GoalType NVARCHAR(50) NOT NULL,
    Target INT NOT NULL,
    CurrentProgress INT NOT NULL DEFAULT 0,
    StartDate DATETIME2 NOT NULL,
    EndDate DATETIME2 NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy UNIQUEIDENTIFIER NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy UNIQUEIDENTIFIER NULL,
    DeletedAt DATETIME2 NULL,
    DeletedBy UNIQUEIDENTIFIER NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    Version ROWVERSION NOT NULL
);
CREATE NONCLUSTERED INDEX IX_ReadingGoals_UserId ON ReadingGoals(UserId) WHERE IsDeleted = 0;
CREATE NONCLUSTERED INDEX IX_ReadingGoals_Status ON ReadingGoals(Status) WHERE IsDeleted = 0;
