CREATE TABLE Highlights (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    BookId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Page INT NULL,
    StartPosition INT NULL,
    EndPosition INT NULL,
    TextSnapshot NVARCHAR(MAX) NOT NULL,
    Color NVARCHAR(20) NOT NULL DEFAULT 'YELLOW',
    Comment NVARCHAR(2000) NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy UNIQUEIDENTIFIER NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy UNIQUEIDENTIFIER NULL,
    DeletedAt DATETIME2 NULL,
    DeletedBy UNIQUEIDENTIFIER NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    Version ROWVERSION NOT NULL
);
CREATE NONCLUSTERED INDEX IX_Highlights_BookId ON Highlights(BookId) WHERE IsDeleted = 0;
CREATE NONCLUSTERED INDEX IX_Highlights_UserId ON Highlights(UserId) WHERE IsDeleted = 0;

CREATE TABLE KnowledgeNotes (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(300) NULL,
    Content NVARCHAR(MAX) NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy UNIQUEIDENTIFIER NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy UNIQUEIDENTIFIER NULL,
    DeletedAt DATETIME2 NULL,
    DeletedBy UNIQUEIDENTIFIER NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    Version ROWVERSION NOT NULL
);
CREATE NONCLUSTERED INDEX IX_KnowledgeNotes_UserId ON KnowledgeNotes(UserId) WHERE IsDeleted = 0;
CREATE NONCLUSTERED INDEX IX_KnowledgeNotes_Status ON KnowledgeNotes(Status) WHERE IsDeleted = 0;

CREATE TABLE Collections (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(200) NOT NULL,
    Description NVARCHAR(1000) NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy UNIQUEIDENTIFIER NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy UNIQUEIDENTIFIER NULL,
    DeletedAt DATETIME2 NULL,
    DeletedBy UNIQUEIDENTIFIER NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    Version ROWVERSION NOT NULL,
    CONSTRAINT UQ_Collections_UserId_Name WHERE IsDeleted = 0 UNIQUE (UserId, Name)
);
CREATE NONCLUSTERED INDEX IX_Collections_UserId ON Collections(UserId) WHERE IsDeleted = 0;

CREATE TABLE CollectionItems (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    CollectionId UNIQUEIDENTIFIER NOT NULL,
    ItemType NVARCHAR(50) NOT NULL,
    ItemId UNIQUEIDENTIFIER NOT NULL,
    [Order] INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT FK_CollectionItems_Collections FOREIGN KEY (CollectionId) REFERENCES Collections(Id),
    CONSTRAINT UQ_CollectionItems_Collection_Item UNIQUE (CollectionId, ItemType, ItemId)
);

CREATE TABLE Tags (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Color NVARCHAR(7) NULL,
    Description NVARCHAR(500) NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CreatedBy UNIQUEIDENTIFIER NULL,
    UpdatedAt DATETIME2 NULL,
    UpdatedBy UNIQUEIDENTIFIER NULL,
    DeletedAt DATETIME2 NULL,
    DeletedBy UNIQUEIDENTIFIER NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    Version ROWVERSION NOT NULL,
    CONSTRAINT UQ_Tags_UserId_Name WHERE IsDeleted = 0 UNIQUE (UserId, Name)
);
CREATE NONCLUSTERED INDEX IX_Tags_UserId ON Tags(UserId) WHERE IsDeleted = 0;

CREATE TABLE BookTags (
    BookId UNIQUEIDENTIFIER NOT NULL,
    TagId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_BookTags_Books FOREIGN KEY (BookId) REFERENCES Books(Id),
    CONSTRAINT FK_BookTags_Tags FOREIGN KEY (TagId) REFERENCES Tags(Id),
    CONSTRAINT PK_BookTags PRIMARY KEY (BookId, TagId)
);

CREATE TABLE HighlightTags (
    HighlightId UNIQUEIDENTIFIER NOT NULL,
    TagId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_HighlightTags_Highlights FOREIGN KEY (HighlightId) REFERENCES Highlights(Id),
    CONSTRAINT FK_HighlightTags_Tags FOREIGN KEY (TagId) REFERENCES Tags(Id),
    CONSTRAINT PK_HighlightTags PRIMARY KEY (HighlightId, TagId)
);

CREATE TABLE KnowledgeNoteBooks (
    NoteId UNIQUEIDENTIFIER NOT NULL,
    BookId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_KnowledgeNoteBooks_Notes FOREIGN KEY (NoteId) REFERENCES KnowledgeNotes(Id),
    CONSTRAINT FK_KnowledgeNoteBooks_Books FOREIGN KEY (BookId) REFERENCES Books(Id),
    CONSTRAINT PK_KnowledgeNoteBooks PRIMARY KEY (NoteId, BookId)
);

CREATE TABLE KnowledgeNoteHighlights (
    NoteId UNIQUEIDENTIFIER NOT NULL,
    HighlightId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_KnowledgeNoteHighlights_Notes FOREIGN KEY (NoteId) REFERENCES KnowledgeNotes(Id),
    CONSTRAINT FK_KnowledgeNoteHighlights_Highlights FOREIGN KEY (HighlightId) REFERENCES Highlights(Id),
    CONSTRAINT PK_KnowledgeNoteHighlights PRIMARY KEY (NoteId, HighlightId)
);
